const DRIVER_STATUSES = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  ACTIVE: "ACTIVE",
  BUSY: "BUSY",
  OFFLINE: "OFFLINE",
  SUSPENDED: "SUSPENDED",
  DEACTIVATED: "DEACTIVATED",
};

const BOOKING_STATUSES = {
  PENDING_ASSIGNMENT: "PENDING_ASSIGNMENT",
  QUEUED: "QUEUED",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAID: "PAID",
  CANCELLED: "CANCELLED",
};

const ASSIGNMENT_STATUSES = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  TIMEOUT: "TIMEOUT",
  CANCELLED: "CANCELLED",
};

const COMMISSION_STATUSES = {
  DUE: "DUE",
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SETTLED: "SETTLED",
};

const LIFECYCLE_REASONS = {
  COMMISSION_OVERDUE: "COMMISSION_OVERDUE",
  COMMISSION_LONG_OVERDUE: "COMMISSION_LONG_OVERDUE",
  MANUAL: "MANUAL",
  NONE: "NONE",
};

const COMPLAINT_STATUSES = {
  OPEN: "OPEN",
  INVESTIGATING: "INVESTIGATING",
  RESOLVED: "RESOLVED",
  DISMISSED: "DISMISSED",
};

const COMPLAINT_PRIORITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

const ASSIGNMENT_MODES = {
  AUTO: "AUTO",
  MANUAL: "MANUAL",
  QUEUE_RETRY: "QUEUE_RETRY",
};

const COMMISSION_RATE = 0.1;

module.exports = {
  DRIVER_STATUSES,
  BOOKING_STATUSES,
  ASSIGNMENT_STATUSES,
  COMMISSION_STATUSES,
  LIFECYCLE_REASONS,
  COMPLAINT_STATUSES,
  COMPLAINT_PRIORITIES,
  ASSIGNMENT_MODES,
  COMMISSION_RATE,
};
