const DRIVER_STATUSES = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  ACTIVE: "ACTIVE",
  BUSY: "BUSY",
  OFFLINE: "OFFLINE",
  SUSPENDED: "SUSPENDED",
  DEACTIVATED: "DEACTIVATED",
};

module.exports = { DRIVER_STATUSES };
